### PR TITLE
Added link to controller enclosure

### PR DESCRIPTION
**Pull request by SteveEasley**
Pointer to 3D printed controller enclosure

### CODE REVIEW

**Review by steven6282 — APPROVED** [review]
Looks like a valid link to me :)

**Comment by DallasEpperson** [comment]
Looks slick. I also just realized the robot's mouth from our logo could look pretty neat as air vents for the enclosure. For example, if our logo were pushed into the surface by a few layers, but the mouth would be completely cut through. https://github.com/ColaMakerspace/ColaMakerspace.github.io/blob/master/images/logo%20120.png  

Also what's your plan for the power cord on the side? Would you want to have a hole in the design, or do you think we should drill a hole after it's printed?

**Comment by SteveEasley** [comment]
Its already printed actually. I had planned to just cut the holes on onsite. 

I put a little thought into trying to emboss the logo at first (at a depth of about 1mm). Then I realized to print the top it needs to go face down (the top of the top on the glass). In that orientation I was not sure how trying to print that void would work. Obviously I could add support material, but wasnt sure what kind of mess it would be to remove it all an not ruin the details in the logo. Maybe you have experiences here?

**Comment by DallasEpperson** [comment]
Ah, yeah that sounds like it would be a pain to print - didn't realize it needed to be printed in that orientation.  

So you already have the item printed?! That's great. Some of us will be at the space today to work on the controller (I'm already here). Feel free to drop by!

**Comment by steven6282** [comment]
So there is a trick that I've used in the past for printing voids without a
support structure mess.

Print the void itself as a solid (30 or 40% infill) object, don't move it
off where it's printed at, then invert the model putting the lid in this
case perfectly over the void.  Before printing, line the void with painters
tape, you just have to make sure to get it nice and tight in all the
corners.  After the lid finishes printing, you should be able to remove the
lid and separate the "void" object since the painters would serve as a
separator.

It's a little painful to get worked out perfectly sometimes, and obviously
wastes more material and time, but provides the cleanest method of printing
a void area.

Support structures work fine too, just every time I've used them it was
never quite perfect after cutting out all the supports.  Still, I think in
this case the slightly rough face the support structures would leave behind
wouldn't really matter.  I've only used the method once when I wanted a
really clean face in a void on something.

**Comment by steven6282** [comment]
Oh, I guess I should also mention though, the void printed method only
works if your design still has enough room for the print head to get around
it :P

**Pull request merged**
