### PR TITLE
OAuth2 Integration

### PR DESCRIPTION
**Pull request by DallasEpperson**
* Added the ability for users to authenticate by logging in to their colamakerspace.com account.  
* Added a configuration json parser  
* Added a dummy config which can be used to generate real configs  
* Added an example of usage at `localhost:8888/secure`
  
If user has multiple google accounts, they are presented with a login prompt like this.  
image
  
If the user successfully logs in, they are taken back to our application with an oauth token in hand. Our application then validates the oauth token against google's server. If successful, application creates an auth session for this user and allows them to pass into secure areas.
image

This code will not allow you to properly authenticate via google's oauth until you fix the `clientId` and `clientSecret` in the config. I also recommend setting a stronger cookieSecret.

### CODE REVIEW

**Comment by DallasEpperson** [comment]
This addresses issue #9.

**Review by steven6282 — COMMENTED** [review]
I'm not really qualified to make suggestions on any of this yet or to look for code problems.  I tested this though and it seems to work, although logout behaves weirdly for me.  If I go to the log out page it says I'm logged out.  Then if I go back to /secure, it redirects me to /#, and seems to auto log me back in.  Then if I go back to /secure again it shows me the "secret area".  I guess that is fine?  I just expected it to prompt me to log in again.  Might just be because I'm doing it within the same chrome session.

Only other comment I can make is I can't remember why it was decided to target Python 2.7, but so far everything works fine on 3.6, except the print statement you added on line 48 of main.py.  If you did that as print(""), it works with 3.6 as well still.  Not that the print statement there is likely that important :P

**Comment by DallasEpperson** [comment]
You shouldn't be able to see the secure area without properly logging in, and you shouldn't be able to properly log in unless your application has valid oauth key & secret codes in its config. If you're able to get to the secure area, I've done something wrong. Let me investigate this evening.

**Comment by steven6282** [comment]
Oh yeah I just set up my own client Id and secret in Google developer
console to use and changed it to allow gmail.com to test.  The first login
worked as expected presenting me with the Google login.

It was after that when logging out then going back to secure that it seemed
to auto log me back in.

**Comment by DallasEpperson** [comment]
> It was after that when logging out then going back to secure that it seemed
to auto log me back in.

Oh, that makes sense then. If you're not authenticated and you try to hit the secure page, it's going to redirect you to google's login page. If you've recently logged in via google's login page, you don't actually have to input credentials, google just says "yeah I know who this bloke is". Then you're redirected back to our application with valid creds.

**Comment by DallasEpperson** [comment]
> If you're not authenticated and you try to hit the secure page, it's going to redirect you to google's login page.

Is that wise, or should I create a page for like "You aren't logged in, click here to log in" or whatever?

**Comment by steven6282** [comment]
I don't see a problem with that.  But, I do think if it does that and it
returns back authenticated it should redirect you back to the page you were
trying to get to.  That way you don't have to try to go to the page twice.

**Review by steven6282 — APPROVED** [review]
So, I guess no one else is going to approve this so I will hehe.  I haven't had time to learn how oauth works myself, but the code itself seems to work an authenticate.  So may as well approve and get it merged so that we can move on to actually securing the members page and such.

**Pull request merged**
